
package juegobthp.interfaz;

public class Bienvenida extends javax.swing.JFrame {

    public Bienvenida() {
        initComponents();
    }
    
    public static void main(String[] args) {
        // Configurar el Look and Feel del sistema
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            // Si falla, usar el Look and Feel por defecto
        }
        
        // Ejecutar la interfaz en el Event Dispatch Thread
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBienv = new javax.swing.JPanel();
        TituloBienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NombreJugador = new javax.swing.JTextField();
        InicioVentJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBienv.setBackground(new java.awt.Color(204, 204, 204));

        TituloBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TituloBienvenida.setForeground(new java.awt.Color(0, 51, 153));
        TituloBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloBienvenida.setText("Bienvenid@ a Batalla Naval");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre Jugador");

        NombreJugador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        InicioVentJuego.setBackground(new java.awt.Color(0, 51, 153));
        InicioVentJuego.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InicioVentJuego.setForeground(new java.awt.Color(204, 204, 204));
        InicioVentJuego.setText("Inicio Juego");
        InicioVentJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioVentJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBienvLayout = new javax.swing.GroupLayout(PanelBienv);
        PanelBienv.setLayout(PanelBienvLayout);
        PanelBienvLayout.setHorizontalGroup(
            PanelBienvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBienvLayout.createSequentialGroup()
                .addGroup(PanelBienvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBienvLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(NombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBienvLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(InicioVentJuego)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        PanelBienvLayout.setVerticalGroup(
            PanelBienvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBienvLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TituloBienvenida)
                .addGap(32, 32, 32)
                .addGroup(PanelBienvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(InicioVentJuego)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBienv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBienv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioVentJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioVentJuegoActionPerformed
        // Mostrar JFrameJuego
    String nombre = NombreJugador.getText();
    
    JFrameJuego ventanaJuego = new JFrameJuego(nombre);
    ventanaJuego.setLocationRelativeTo(null);
    ventanaJuego.setVisible(true);
    this.dispose();  // Cierra la ventana de bienvenida
    // Cerrar la ventana de bienvenida
    }//GEN-LAST:event_InicioVentJuegoActionPerformed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InicioVentJuego;
    private javax.swing.JTextField NombreJugador;
    private javax.swing.JPanel PanelBienv;
    private javax.swing.JLabel TituloBienvenida;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
